<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerK55oh1S\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerK55oh1S/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerK55oh1S.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerK55oh1S\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerK55oh1S\App_KernelDevDebugContainer([
    'container.build_hash' => 'K55oh1S',
    'container.build_id' => '9ebf5186',
    'container.build_time' => 1621272125,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerK55oh1S');
